// <auto-generated />
using System;
using Learnable.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learnable.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110183431_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learnable.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("AssetsProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AssetsProfileId")
                        .HasName("PK__Assets__278E59AF58F39BA2");

                    b.HasIndex("RepoId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E54864800A75C89");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassJoinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId")
                        .HasName("PK__Class__CB1927C0735CA6EB");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "ClassJoinName" }, "UQ__Class__F103E8E0B0547C57")
                        .IsUnique();

                    b.ToTable("Class");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.ClassStudent", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("StudentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("ClassId", "StudentId")
                        .HasName("PK__ClassStu__48357579EC94B403");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassStudent");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExamId")
                        .HasName("PK__Exam__297521C7F8D3E0FA");

                    b.HasIndex("RepoId");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Mark", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExamStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Marks")
                        .HasColumnType("int");

                    b.HasKey("ExamId", "StudentId")
                        .HasName("PK__Marks__AA59737E7EEE6756");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromptText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Prompt__3214EC0795D7F6C9");

                    b.ToTable("Prompt");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RepoCertification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RepoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("RepoId")
                        .HasName("PK__Reposito__856806780424CB75");

                    b.HasIndex("ClassId");

                    b.ToTable("Repository");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.RequestNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NotificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sent");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__RequestN__20CF2E128EDF9FB2");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("RequestNotification");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52B996171B967");

                    b.HasIndex(new[] { "UserId" }, "UQ__Student__1788CC4D4FFBBC12")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfileId")
                        .HasName("PK__Teacher__290C88E41AE75428");

                    b.HasIndex(new[] { "UserId" }, "UQ__Teacher__1788CC4DFD7991BE")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CB2415AFE");

                    b.HasIndex(new[] { "Username" }, "UQ__User__536C85E401B99EE3")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105340B8B0374")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Repository", "Repo")
                        .WithMany("Assets")
                        .HasForeignKey("RepoId")
                        .HasConstraintName("FK__Assets__RepoId__440B1D61");

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Class", "Class")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__AuditLog__ClassI__4F7CD00D");

                    b.HasOne("Learnable.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AuditLog__UserId__4E88ABD4");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Class", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Class__TeacherId__35BCFE0A");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.ClassStudent", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassStud__Class__3A81B327");

                    b.HasOne("Learnable.Domain.Entities.Student", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassStud__Stude__3B75D760");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Exam", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Repository", "Repo")
                        .WithMany("Exams")
                        .HasForeignKey("RepoId")
                        .HasConstraintName("FK__Exam__RepoId__46E78A0C");

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Mark", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Exam", "Exam")
                        .WithMany("Marks")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Marks__ExamId__49C3F6B7");

                    b.HasOne("Learnable.Domain.Entities.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Marks__StudentId__4AB81AF0");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Repository", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.Class", "Class")
                        .WithMany("Repositories")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Repositor__Class__403A8C7D");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.RequestNotification", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.User", "Receiver")
                        .WithMany("RequestNotificationReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__RequestNo__Recei__5535A963");

                    b.HasOne("Learnable.Domain.Entities.User", "Sender")
                        .WithMany("RequestNotificationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__RequestNo__Sende__5441852A");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Student", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Learnable.Domain.Entities.Student", "UserId")
                        .HasConstraintName("FK__Student__UserId__300424B4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("Learnable.Domain.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("Learnable.Domain.Entities.Teacher", "UserId")
                        .HasConstraintName("FK__Teacher__UserId__2B3F6F97");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Class", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ClassStudents");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Student", b =>
                {
                    b.Navigation("ClassStudents");

                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Learnable.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RequestNotificationReceivers");

                    b.Navigation("RequestNotificationSenders");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
